// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-zy1P6MAidLDDOr8JpRMEPc00bQP_fIU',
    appId: '1:552537720302:web:b34eef0095924ef907baff',
    messagingSenderId: '552537720302',
    projectId: 'tastie-1701f',
    authDomain: 'tastie-1701f.firebaseapp.com',
    storageBucket: 'tastie-1701f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDShxNya7wGRS0j0njUJKb5AZS1SmVb5Fw',
    appId: '1:552537720302:android:794d06e79be210dd07baff',
    messagingSenderId: '552537720302',
    projectId: 'tastie-1701f',
    storageBucket: 'tastie-1701f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe_Anm3oaaqi4zqUQMQgo0nNuMkQdTtsk',
    appId: '1:552537720302:ios:b596404d5f4f4ff107baff',
    messagingSenderId: '552537720302',
    projectId: 'tastie-1701f',
    storageBucket: 'tastie-1701f.firebasestorage.app',
    iosClientId: '552537720302-uv2m7rlbtbh46buqfiag73io9aosijfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.tastie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe_Anm3oaaqi4zqUQMQgo0nNuMkQdTtsk',
    appId: '1:552537720302:ios:b596404d5f4f4ff107baff',
    messagingSenderId: '552537720302',
    projectId: 'tastie-1701f',
    storageBucket: 'tastie-1701f.firebasestorage.app',
    iosClientId: '552537720302-uv2m7rlbtbh46buqfiag73io9aosijfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.tastie',
  );
}
